### ISSUE TITLE
Underscore dependencie

### ISSUE THREAD

**Issue by herlon214** [tranquochuy/unescape-html#1]
After I install with npm it throws me an error:

``` javascript
Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by herlon214** [comment]
I think you forgot to install the "underscore" using --save.
Whatever, I'm not using this lib anymore.

**Comment by huytr4n** [comment]
Thanks, man. Did you create the pull request for me?

**Comment by huytr4n** [comment]
Fixed
